all: help

help:
	@echo try one of these commands:
	@echo "  compile .... compiles templates into one file"
	
compile:
	@echo "compiling..."
	cat ./template/header.html ./template/guide* ./template/footer.html > ./index.html